// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MVskewt_c
double MVskewt_c(const arma::mat& Y, const arma::mat& M, const arma::mat& A, const arma::mat& Sigma, const arma::mat& Psi, double nu, int n, int p, const StringVector& log_pdf_type, const StringVector& Sigma_type);
RcppExport SEXP _STMATREG_MVskewt_c(SEXP YSEXP, SEXP MSEXP, SEXP ASEXP, SEXP SigmaSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP nSEXP, SEXP pSEXP, SEXP log_pdf_typeSEXP, SEXP Sigma_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type log_pdf_type(log_pdf_typeSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type Sigma_type(Sigma_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(MVskewt_c(Y, M, A, Sigma, Psi, nu, n, p, log_pdf_type, Sigma_type));
    return rcpp_result_gen;
END_RCPP
}
// MST_logpdf_c
double MST_logpdf_c(List Y, List M, List A, List Sigma, const arma::mat& Psi, double nu, const StringVector& log_pdf_type, const StringVector& Sigma_type);
RcppExport SEXP _STMATREG_MST_logpdf_c(SEXP YSEXP, SEXP MSEXP, SEXP ASEXP, SEXP SigmaSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP log_pdf_typeSEXP, SEXP Sigma_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type M(MSEXP);
    Rcpp::traits::input_parameter< List >::type A(ASEXP);
    Rcpp::traits::input_parameter< List >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type log_pdf_type(log_pdf_typeSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type Sigma_type(Sigma_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(MST_logpdf_c(Y, M, A, Sigma, Psi, nu, log_pdf_type, Sigma_type));
    return rcpp_result_gen;
END_RCPP
}
// DEC1_obj_fun_c
double DEC1_obj_fun_c(double DEC1, List Estep_output, const NumericMatrix& beta_mat, NumericVector A_value, const arma::mat& Psi_inv_value, double DEC2);
RcppExport SEXP _STMATREG_DEC1_obj_fun_c(SEXP DEC1SEXP, SEXP Estep_outputSEXP, SEXP beta_matSEXP, SEXP A_valueSEXP, SEXP Psi_inv_valueSEXP, SEXP DEC2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type DEC1(DEC1SEXP);
    Rcpp::traits::input_parameter< List >::type Estep_output(Estep_outputSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type beta_mat(beta_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_value(A_valueSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Psi_inv_value(Psi_inv_valueSEXP);
    Rcpp::traits::input_parameter< double >::type DEC2(DEC2SEXP);
    rcpp_result_gen = Rcpp::wrap(DEC1_obj_fun_c(DEC1, Estep_output, beta_mat, A_value, Psi_inv_value, DEC2));
    return rcpp_result_gen;
END_RCPP
}
// DEC2_obj_fun_c
double DEC2_obj_fun_c(double DEC2, List Estep_output, const NumericMatrix& beta_mat, NumericVector A_value, const arma::mat& Psi_inv_value, double DEC1);
RcppExport SEXP _STMATREG_DEC2_obj_fun_c(SEXP DEC2SEXP, SEXP Estep_outputSEXP, SEXP beta_matSEXP, SEXP A_valueSEXP, SEXP Psi_inv_valueSEXP, SEXP DEC1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type DEC2(DEC2SEXP);
    Rcpp::traits::input_parameter< List >::type Estep_output(Estep_outputSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type beta_mat(beta_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_value(A_valueSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Psi_inv_value(Psi_inv_valueSEXP);
    Rcpp::traits::input_parameter< double >::type DEC1(DEC1SEXP);
    rcpp_result_gen = Rcpp::wrap(DEC2_obj_fun_c(DEC2, Estep_output, beta_mat, A_value, Psi_inv_value, DEC1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STMATREG_MVskewt_c", (DL_FUNC) &_STMATREG_MVskewt_c, 10},
    {"_STMATREG_MST_logpdf_c", (DL_FUNC) &_STMATREG_MST_logpdf_c, 8},
    {"_STMATREG_DEC1_obj_fun_c", (DL_FUNC) &_STMATREG_DEC1_obj_fun_c, 6},
    {"_STMATREG_DEC2_obj_fun_c", (DL_FUNC) &_STMATREG_DEC2_obj_fun_c, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_STMATREG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
